/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 clouds.gltf --types 
Author: Bastien Genbrugge (https://sketchfab.com/bastienBGR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ship-in-clouds-c475323dc7f24e26ba2009c08c8e1941
Title: Ship in Clouds
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Sky_Mat_0: THREE.Mesh
    Boot_Finaal_1_Boot_Finaal_0: THREE.Mesh
    Cloud_Poly_Poly_0: THREE.Mesh
    Cloud_1_Cloud_1_0: THREE.Mesh
    Cloud_2_Cloud_2_0: THREE.Mesh
    Cloud_3_Cloud_3_0: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    Boot_Finaal: THREE.MeshStandardMaterial
    Poly: THREE.MeshStandardMaterial
    Cloud_1: THREE.MeshStandardMaterial
    Cloud_2: THREE.MeshStandardMaterial
    Cloud_3: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[];
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const gltf = useGLTF("/Clouds/clouds.gltf") as unknown as GLTFResult;
const { nodes, materials } = gltf;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Sky_Mat_0.geometry} material={materials.material} position={[51.637, 0, -817.579]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Boot_Finaal_1_Boot_Finaal_0.geometry} material={materials.Boot_Finaal} position={[7.534, -7.801, -688.476]} rotation={[0, -0.6, 0]} />
          <mesh geometry={nodes.Cloud_Poly_Poly_0.geometry} material={materials.Poly} />
          <mesh geometry={nodes.Cloud_1_Cloud_1_0.geometry} material={materials.Cloud_1} position={[-102.342, -152.023, -1209.99]} rotation={[1.917, 0.433, 0.911]} scale={1.5} />
          <mesh geometry={nodes.Cloud_2_Cloud_2_0.geometry} material={materials.Cloud_2} position={[333.052, -63.933, -1541.733]} rotation={[-2.901, 0.214, -1.167]} scale={1.5} />
          <mesh geometry={nodes.Cloud_3_Cloud_3_0.geometry} material={materials.Cloud_3} position={[339.375, -70.968, -1571.745]} rotation={[2.892, -1.308, 3.083]} scale={1.189} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Clouds/clouds.gltf')
