/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CrtMonitor.gltf --types 
Author: Dan (https://sketchfab.com/fizyman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crt-computer-monitor-f2ff0013f86e4cd0a2aee183a23bdfee
Title: CRT Computer Monitor
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    CRT_Monitor_monitor_glass_0: THREE.Mesh
    CRT_Monitor_monitor_plastic_0: THREE.Mesh
  }
  materials: {
    monitor_glass: THREE.MeshStandardMaterial
    monitor_plastic: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[];
}

export default function CrtMonitor(props: JSX.IntrinsicElements['group']) {
  const gltf = useGLTF("/CRT/CrtMonitor.gltf") as unknown as GLTFResult;
const { nodes, materials, animations } = gltf;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, -7.127, 5.522]} rotation={[-Math.PI / 2, 0, 0]} scale={10}>
          <mesh geometry={nodes.CRT_Monitor_monitor_glass_0.geometry} material={materials.monitor_glass} />
          <mesh geometry={nodes.CRT_Monitor_monitor_plastic_0.geometry} material={materials.monitor_plastic} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/CRT/CrtMonitor.gltf')
