/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 forest.gltf --types 
Author: patrix (https://sketchfab.com/patrix)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/forest-demo-1269b7e00f9d4ce09931c0c95967bc33
Title: Forest Demo
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    forest_forest_0: THREE.Mesh
  }
  materials: {
    forest: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[];
}

export default function Forest(props: JSX.IntrinsicElements['group']) {
    const gltf = useGLTF(`${import.meta.env.BASE_URL}/Forest/forest_mr.glb`) as unknown as GLTFResult;
    const { nodes, materials } = gltf;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.forest_forest_0.geometry} material={materials.forest} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(`${import.meta.env.BASE_URL}/Forest/forest_mr.gltf`)
