/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fridge.gltf --types 
Author: SilkevdSmissen (https://sketchfab.com/SilkevdSmissen)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/mercenary-hideout-spot-5c8edf1cba5c465492e15a5f1d840ec2
Title: Mercenary Hideout Spot
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    FridgeRack_low_tv_high_default_0: THREE.Mesh
    ['TvScreen_low_04_-_Default_0']: THREE.Mesh
    ['TvSideButton_low_04_-_Default_0']: THREE.Mesh
    ['TvSides_low_04_-_Default_0']: THREE.Mesh
    ['TvBody_low_04_-_Default_0']: THREE.Mesh
    ['TvButtons_low_04_-_Default_0']: THREE.Mesh
    ['TvBottom_low_04_-_Default_0']: THREE.Mesh
    ['TvAntenna_low_04_-_Default_0']: THREE.Mesh
    VhsButtons_low_Ceramic_0: THREE.Mesh
    VhsBackBorder_low_Ceramic_0: THREE.Mesh
    VhsBody_low_Ceramic_0: THREE.Mesh
    VhsButtonsBack_low_Ceramic_0: THREE.Mesh
    VhsFront_low_Ceramic_0: THREE.Mesh
    VhsScreen_low_Ceramic_0: THREE.Mesh
    VhsShinyRight_low_Ceramic_0: THREE.Mesh
    FridgeCalendarPapers_low_tv_high_default_0: THREE.Mesh
    FridgeCalendarHelix_low_tv_high_default_0: THREE.Mesh
    FridgeCalendarHanger_low_tv_high_default_0: THREE.Mesh
    FridgePapers_low_tv_high_default_0: THREE.Mesh
    FridgeMagnets_low_tv_high_default_0: THREE.Mesh
    FridgeLetterMagnets_low_tv_high_default_0: THREE.Mesh
    VhsBoxes_low_tv_high_default_0: THREE.Mesh
    VhsTape_low_tv_high_default_0: THREE.Mesh
    FridgeDoor_low_Wall_Paint_0: THREE.Mesh
    FridgePull_low_Wall_Paint_0: THREE.Mesh
    FridgeHinges_low_Wall_Paint_0: THREE.Mesh
    FridgeBody_low_Wall_Paint_0: THREE.Mesh
    FridgeBottomCurved_low_Wall_Paint_0: THREE.Mesh
    fridgeBottomStraight_low_Wall_Paint_0: THREE.Mesh
    FridgeButtons_low_Wall_Paint_0: THREE.Mesh
    FridgeHandle_low_Wall_Paint_0: THREE.Mesh
    FridgeFrilec_low_Wall_Paint_0: THREE.Mesh
    Wires_low_tv_high_default_0: THREE.Mesh
    PowerPlug_low_tv_high_default_0: THREE.Mesh
    PowerPlugMetal_low_tv_high_default_0: THREE.Mesh
    VhsBoxes4_low_tv_high_default_0: THREE.Mesh
    VhsTape4_low_tv_high_default_0: THREE.Mesh
    VhsBoxes3_low_tv_high_default_0: THREE.Mesh
    VhsTape3_low_tv_high_default_0: THREE.Mesh
    VhsBoxes2_low_tv_high_default_0: THREE.Mesh
    VhsTape2_low_tv_high_default_0: THREE.Mesh
    PowerPlugMetal2_low_tv_high_default_0: THREE.Mesh
    PowerPlug2_low_tv_high_default_0: THREE.Mesh
  }
  materials: {
    tv_high_default: THREE.MeshStandardMaterial
    ['04_-_Default']: THREE.MeshStandardMaterial
    Ceramic: THREE.MeshStandardMaterial
    Wall_Paint: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[];
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const gltf = useGLTF("/FridgeComputer/fridge.gltf") as unknown as GLTFResult;
  const { nodes, materials, animations } = gltf;
  return (
    <group {...props} dispose={null}>
      <group position={[16.302, 108.887, 18.649]} rotation={[0, -0.175, 0]} scale={[1.029, 0.972, 1.029]}>
        <mesh geometry={nodes['TvScreen_low_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[0, 0, -1.949]} />
      </group>
      <group position={[19.099, 107.454, 2.79]} rotation={[0, -0.174, 0]} scale={[1, 0.945, 1]}>
        <mesh geometry={nodes['TvBody_low_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[0, 1.372, 13.725]} />
      </group>
      <group position={[31.573, 119.968, -10.284]} rotation={[-Math.PI / 2, 0, 2.967]} scale={[0.176, 0.029, 0.176]}>
        <mesh geometry={nodes['TvAntenna_low_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[48.35, -38.387, -47]} />
      </group>
      <group position={[-21.47, 92.877, -9.318]} rotation={[Math.PI, -Math.PI / 9, Math.PI]} scale={[0.917, 0.917, 1.381]}>
        <mesh geometry={nodes.VhsButtonsBack_low_Ceramic_0.geometry} material={materials.Ceramic} position={[-9.932, 0, -0.533]} />
      </group>
      <group position={[-1.041, 10.648, 29.039]} rotation={[1.571, 0, Math.PI]}>
        <mesh geometry={nodes.FridgeBottomCurved_low_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[-0.054, 34.695, -7.355]} />
      </group>
      <mesh geometry={nodes.FridgeRack_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-0.984, 86.771, 5.093]} rotation={[-Math.PI / 2, 0, 0.064]} />
      <mesh geometry={nodes['TvSideButton_low_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[35.235, 108.035, 14.144]} rotation={[Math.PI, -1.396, Math.PI]} scale={[0.92, 0.92, 5.328]} />
      <mesh geometry={nodes['TvSides_low_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[2.661, 106.02, -0.247]} rotation={[Math.PI, -1.396, Math.PI]} />
      <mesh geometry={nodes['TvButtons_low_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[9.749, 95.394, 18.282]} rotation={[-Math.PI / 2, 0, -0.175]} />
      <mesh geometry={nodes['TvBottom_low_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[21.133, 90.08, -8.748]} rotation={[0, -0.175, 0]} scale={[1, 1.189, 1]} />
      <mesh geometry={nodes.VhsButtons_low_Ceramic_0.geometry} material={materials.Ceramic} position={[-34.761, 94.095, 23.027]} rotation={[0, Math.PI / 9, 0]} scale={[1.2, 1.2, 1.055]} />
      <mesh geometry={nodes.VhsBackBorder_low_Ceramic_0.geometry} material={materials.Ceramic} position={[-32.66, 91.647, -6.28]} rotation={[-Math.PI, -Math.PI / 9, -Math.PI]} scale={[1.328, 1.328, 1.167]} />
      <mesh geometry={nodes.VhsBody_low_Ceramic_0.geometry} material={materials.Ceramic} position={[-22.936, 87.576, 4.452]} rotation={[-Math.PI / 2, 0, Math.PI / 9]} scale={[1.304, 1.348, 1.335]} />
      <mesh geometry={nodes.VhsFront_low_Ceramic_0.geometry} material={materials.Ceramic} position={[-22.936, 87.576, 4.452]} rotation={[-Math.PI / 2, 0, Math.PI / 9]} scale={[1.304, 1.348, 1.335]} />
      <mesh geometry={nodes.VhsScreen_low_Ceramic_0.geometry} material={materials.Ceramic} position={[-27.952, 89.873, 20.522]} rotation={[0, Math.PI / 9, 0]} scale={[1.355, 0.517, 1.064]} />
      <mesh geometry={nodes.VhsShinyRight_low_Ceramic_0.geometry} material={materials.Ceramic} position={[-4.581, 91.595, 12.087]} rotation={[0, Math.PI / 9, 0]} scale={[1.328, 1.33, 1.167]} />
      <mesh geometry={nodes.FridgeCalendarPapers_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[13.269, 42.787, 35.011]} rotation={[-0.076, -0.009, 0.116]} scale={0.852} />
      <mesh geometry={nodes.FridgeCalendarHelix_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[0.942, 45.684, 34.749]} rotation={[-Math.PI / 2, 1.454, 0]} />
      <mesh geometry={nodes.FridgeCalendarHanger_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[10.171, 54.37, 34.645]} />
      <mesh geometry={nodes.FridgePapers_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-18.083, 68.425, 35.069]} rotation={[-0.087, 0, -0.221]} scale={0.852} />
      <mesh geometry={nodes.FridgeMagnets_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[19.371, 77.969, 34.295]} />
      <mesh geometry={nodes.FridgeLetterMagnets_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-19.561, 77.991, 34.301]} rotation={[0, 0, 0.088]} scale={0.06} />
      <mesh geometry={nodes.VhsBoxes_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-32.053, 95.528, 1.141]} rotation={[-Math.PI / 2, 0, Math.PI / 3]} scale={1.248} />
      <mesh geometry={nodes.VhsTape_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-29.914, 96.758, 2.38]} rotation={[0, Math.PI / 3, 0]} />
      <mesh geometry={nodes.FridgeDoor_low_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[-1.095, 7.885, -5.641]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.FridgePull_low_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[-16.052, 54.489, 38.577]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.FridgeHinges_low_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[-30.344, 74.764, 25.077]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1, 1, 0.668]} />
      <mesh geometry={nodes.FridgeBody_low_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[-1.101, 7.885, -5.406]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.fridgeBottomStraight_low_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[-1.166, 2.768, 4.637]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1.239]} />
      <mesh geometry={nodes.FridgeButtons_low_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[-8.738, 49.908, -18.829]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.FridgeHandle_low_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[-7.074, 96.439, 6.549]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.FridgeFrilec_low_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[-0.613, 70.544, 34.146]} scale={[0.727, 0.754, 0.885]} />
      <mesh geometry={nodes.Wires_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-0.188, 87.832, -16.001]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.PowerPlug_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[39.187, 21.968, -2.971]} rotation={[1.547, 0, Math.PI / 3]} scale={[0.815, 1.166, 0.912]} />
      <mesh geometry={nodes.PowerPlugMetal_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[39.187, 21.968, -2.971]} rotation={[1.547, 0, Math.PI / 3]} scale={[0.815, 1.166, 0.912]} />
      <mesh geometry={nodes.VhsBoxes4_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-31.616, 98.11, 2.105]} rotation={[-Math.PI / 2, 0, Math.PI / 6]} scale={1.248} />
      <mesh geometry={nodes.VhsTape4_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-30.383, 99.341, 4.248]} rotation={[0, Math.PI / 6, 0]} />
      <mesh geometry={nodes.VhsBoxes3_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-31.984, 100.717, 1.201]} rotation={[-Math.PI / 2, 0, 0.175]} scale={1.248} />
      <mesh geometry={nodes.VhsTape3_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-31.558, 101.947, 3.636]} rotation={[0, 0.175, 0]} />
      <mesh geometry={nodes.VhsBoxes2_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-29.777, 103.372, 0.087]} rotation={[-Math.PI / 2, 0, 0.436]} scale={1.248} />
      <mesh geometry={nodes.VhsTape2_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[-28.736, 104.603, 2.329]} rotation={[0, 0.436, 0]} />
      <mesh geometry={nodes.PowerPlugMetal2_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[25.331, 1.333, 40.599]} rotation={[-0.023, -1.027, -0.019]} scale={[0.815, 1.166, 0.912]} />
      <mesh geometry={nodes.PowerPlug2_low_tv_high_default_0.geometry} material={materials.tv_high_default} position={[25.331, 1.333, 40.599]} rotation={[-0.023, -1.027, -0.019]} scale={[0.815, 1.166, 0.912]} />
    </group>
  )
}

useGLTF.preload('/FridgeComputer/fridge.gltf')
