/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 terminal.gltf --types 
Author: Chris Sweetwood (https://sketchfab.com/ChrisSweetwood)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/computer-terminal-b3a26b00c5b04eedad0a1cdca884130f
Title: Computer Terminal
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Comp_Screen000_TerminalMaterial_0: THREE.Mesh
    Plane_ShadowMaterial_0: THREE.Mesh
    Plane_BackgroundMaterial_0: THREE.Mesh
    Comp_Screen002_TerminalMaterial_0: THREE.Mesh
  }
  materials: {
    TerminalMaterial: THREE.MeshStandardMaterial
    ShadowMaterial: THREE.MeshStandardMaterial
    BackgroundMaterial: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[];
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const gltf = useGLTF("/Terminal/terminal.gltf") as unknown as GLTFResult;
const { nodes, materials, animations } = gltf;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -5.373, -41.867]} rotation={[-Math.PI / 2, 0, 0]} scale={120.572}>
            <mesh geometry={nodes.Plane_ShadowMaterial_0.geometry} material={materials.ShadowMaterial} />
            <mesh geometry={nodes.Plane_BackgroundMaterial_0.geometry} material={materials.BackgroundMaterial} />
          </group>
          <mesh geometry={nodes.Comp_Screen000_TerminalMaterial_0.geometry} material={materials.TerminalMaterial} position={[18.161, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={212.25} />
          <mesh geometry={nodes.Comp_Screen002_TerminalMaterial_0.geometry} material={materials.TerminalMaterial} position={[18.161, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={212.25} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Terminal/terminal.gltf')
